/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../../common";

export interface BNPairingPrecompileCostEstimatorInterface extends Interface {
  getFunction(
    nameOrSignature: "baseCost" | "getGasCost" | "perPairCost" | "run"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "baseCost", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getGasCost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "perPairCost",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "run", values?: undefined): string;

  decodeFunctionResult(functionFragment: "baseCost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGasCost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "perPairCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "run", data: BytesLike): Result;
}

export interface BNPairingPrecompileCostEstimator extends BaseContract {
  connect(runner?: ContractRunner | null): BNPairingPrecompileCostEstimator;
  waitForDeployment(): Promise<this>;

  interface: BNPairingPrecompileCostEstimatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  baseCost: TypedContractMethod<[], [bigint], "view">;

  getGasCost: TypedContractMethod<[pairCount: BigNumberish], [bigint], "view">;

  perPairCost: TypedContractMethod<[], [bigint], "view">;

  run: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "baseCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGasCost"
  ): TypedContractMethod<[pairCount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "perPairCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "run"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
